{% set name = "cadwyn" %}
{% set version = "5.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cadwyn-{{ version }}.tar.gz
  sha256: ff1ae3b23ea7bb0849f345ee78e20a102f7d9bb96e9d9dff0f66e47b4f61910d

build:
  noarch: python
  entry_points:
    - cadwyn = cadwyn.__main__:app
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - fastapi >=0.112.4
    - starlette >=0.30.0
    - pydantic >=2.11.0
    - jinja2 >=3.1.2
    # for all python to stay noarch: python
    - backports.strenum >=1.3.1,<2
    - typing_extensions >=4.8.0
    - typing-inspection >=0.4.0

test:
  imports:
    - cadwyn
  commands:
    - pip check
    - cadwyn --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/zmievsa/cadwyn
  summary: Production-ready community-driven modern Stripe-like API versioning in FastAPI
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/zmievsa/cadwyn
  doc_url: https://docs.cadwyn.dev/

extra:
  recipe-maintainers:
    - xylar
