{% set name = "cadwyn" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cadwyn-{{ version }}.tar.gz
  sha256: 9ce6affe2c01c7b35971cdeaa7ff57675ec6626b4fe6a7f1c830e021db76aa82

build:
  noarch: python
  entry_points:
    - cadwyn = cadwyn.__main__:app
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - fastapi >=0.121.1
    - starlette >=0.30.0
    - pydantic >=2.11.0
    - jinja2 >=3.1.2
    # for all python to stay noarch: python
    - backports.strenum >=1.3.1,<2
    - typing_extensions >=4.8.0
    - typing-inspection >=0.4.0

test:
  imports:
    - cadwyn
  commands:
    - pip check
    - cadwyn --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/zmievsa/cadwyn
  summary: Production-ready community-driven modern Stripe-like API versioning in FastAPI
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/zmievsa/cadwyn
  doc_url: https://docs.cadwyn.dev/

extra:
  recipe-maintainers:
    - xylar
