schema_version: 1

context:
  name: cadwyn
  version: "6.0.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/cadwyn-${{ version }}.tar.gz
  sha256: bf9b7228a5f809ab19daac569a9877218e2356975a0a4908273b6b56bd7820ef

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - cadwyn = cadwyn.__main__:app

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    # limit becasue of https://github.com/zmievsa/cadwyn/issues/326
    - fastapi >=0.121.1,<0.128.4
    - starlette >=0.30.0
    - pydantic >=2.11.0
    - jinja2 >=3.1.2
    - typing_extensions >=4.8.0
    - typing-inspection >=0.4.0
    # for all python to stay noarch: python
    - backports.strenum >=1.3.1,<2
tests:
  - python:
      imports:
        - cadwyn
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check
      - cadwyn --help

about:
  summary: Production-ready community-driven modern Stripe-like API versioning in FastAPI
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/zmievsa/cadwyn
  repository: https://github.com/zmievsa/cadwyn
  documentation: https://docs.cadwyn.dev/

extra:
  recipe-maintainers:
    - xylar
